### ISSUE TITLE
How to create multiple environments as in A3C/A2C

### ISSUE THREAD

**Issue by dannysdeng** [openai/retro-contest#13]
It's mentioned in [https://contest.openai.com/details](url) that 
> You can only have one environment per process due to limitations of the libretro API. If you want more than that, you can create subprocesses.

I'd like to know what's the proper way to create subprocesses in docker for submitting to the test server. As shown in the [sample codes](https://github.com/openai/retro-baselines/blob/master/agents/sonic_util.py), the environment API is 

    > import gym_remote.client as grc
    > env = grc.RemoteEnv('tmp/sock')

But when I do:

    > def make_env():
    >    def _thunk():
    >        print('Initiation...')
    >        env = grc.RemoteEnv('tmp/sock')
    >        print('ok')
    >        return env
    >    return _thunk

    > from baselines.common.vec_env.subproc_vec_env import SubprocVecEnv
    > num_processes = 2
    > envs = [make_env() for i in range(num_processes)]
    > envs = SubprocVecEnv(envs)

The second environment hangs when I run locally in my docker. It seems to also hang on the submission server.

However, this works fine locally in my docker:

    > from retro_contest.local import make
    > def make_env():
    >    def _thunk():
    >        print('Initiation...')
    >        env = make(game='SonicTheHedgehog-Genesis', state='LabyrinthZone.Act1')
    >        print('ok')
    >        return env
    >    return _thunk

    > from baselines.common.vec_env.subproc_vec_env import SubprocVecEnv
    > num_processes = 2
    > envs = [make_env() for i in range(num_processes)]
    > envs = SubprocVecEnv(envs)

Any useful suggestion/code snippets that might point me to the right direction is much appreciated.

**Comment by endrift** [comment]
You cannot do this--there is only one environment per worker. You can train on multiple environments but not evaluate.

**Comment by dannysdeng** [comment]
@endrift  Thanks for the clarification.
