### ISSUE TITLE
env.step is slow

### ISSUE THREAD

**Issue by tdb-alcorn** [openai/retro-contest#18]
I'm finding that my training episodes take many seconds (sometimes as much as 30s) each to run. I believe the culprit is `env.step`:

```
%timeit env.step(env.action_space.sample())
> 3.21 ms ± 50.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

Multiply that by a thousands of steps per episode and it explains why episodes take so long to run.
Is there anything I can do to get `env.step` running faster? Is it rate-limited?

p.s. kudos on making a great emulator!

**Comment by endrift** [comment]
That doesn't sound slow. It's running a console for an emulated 66ms, which is pretty intensive. That's 20x real speed.

**Comment by tdb-alcorn** [comment]
Fair enough, thanks for explaining
