### ISSUE TITLE
module 'retro' has no attribute 'STATE_DEFAULT'

### ISSUE THREAD

**Issue by jamesrichter** [openai/retro-contest#26]
Hi, I tried to run random-agent-contest.py and got this weird error.

Traceback (most recent call last):
  File "random-agent-contest.py", line 1, in <module>
    from retro_contest.local import make
  File "/home/jim/Downloads/retro-contest/support/retro_contest/local.py", line 6, in <module>
    def make(game, state=retro.STATE_DEFAULT, discrete_actions=False, bk2dir=None):
AttributeError: module 'retro' has no attribute 'STATE_DEFAULT'

Does anyone know why?

**Comment by endrift** [comment]
This is due to the API change between 0.5 and 0.6. I just released 0.6 last week and forgot to push the stashed changes I had to fix this. Pushed now.
