### ISSUE TITLE
Are the test levels available?

### ISSUE THREAD

**Issue by wilkinsmicawber** [openai/retro-contest#29]
I would like to expand the number of levels the agent I am training to play sonic has to test on while allowing for comparisons to be drawn to the results of the contest, if I perhaps discover some method that beats a previously unbeatable level. Have you made available the test levels used in the competition for download?

**Comment by endrift** [comment]
Patches against the base ROMs are located here: https://github.com/openai/retro/tree/master/retro/data/contrib

They're in XDelta format so you'll need a patching utility to generate them from the generic Sonic ROMs.
