### ISSUE TITLE
The base TensorFlow docker images do not have Cuda configured correctly

### ISSUE THREAD

**Issue by praveen-palanisamy** [openai/retro-contest#6]
### The Issue:
`import tensorflow` fails with `ImportError: libcuda.so.1: cannot open shared object file: No such file or directory`  using `openai/retro-agent:tensorflow` as the base docker image.

The issue exists in `openai/retro-agent:tensorflow-1.4` also. Haven't tested other tags.

**Comment by endrift** [comment]
You need to use nvidia-docker (--runtime nvidia), at which point it will work properly.

**Comment by endrift** [comment]
Were you passing `-N`?

**Comment by tristansokol** [comment]
I'm having the same issue, trying to get the baseline rainbow agent running
```
retro-contest run --agent $DOCKER_REGISTRY/rainbow-agent:v1 \
    --results-dir results --no-nv  --use-host-data\
    SonicTheHedgehog-Genesis GreenHillZone.Act1
```
It seems like you need to build  a different image to test locally if you don't have a gpu (like my macbook) but I am not sure how since I am already using `tensorflow` not `tensorflow-gpu`

**Comment by tristansokol** [comment]
@HanSeoulOh, not yet (since I believe that I am still building CPU utilizing images & have tried using some other images that start install tensorflow). My current hypothesis is that tensorflow on my machine just can't find my installed Cuda libraries. I'm kind of lost though.

**Comment by endrift** [comment]
If you have an Nvidia GPU with nvidia-docker2 installed you should not pass --no-nv.
