### ISSUE TITLE
retro-contest does not exit with an appropriate status

### ISSUE THREAD

**Issue by ConradBailey** [openai/retro-contest#9]
I've been scripting my job submission process, and in that script I test the exit status of commands like `retro-contest submit` and `retro-contest login`. I know in particular that these two commands don't exit with non-zero statuses when errors have occurred, and I believe this issue extends to other commands as well. I know it is only convention, but it is a fairly common convention.

**Comment by endrift** [comment]
Good call. I'll add this soon.
